FROM python:3.12-alpine
ENV http_proxy http://10.8.94.101:3128 
ENV https_proxy http://10.8.94.101:3128 
WORKDIR /app

COPY requirements-bot.txt requirements-bot.txt

RUN pip install -r requirements-bot.txt
