services:
  test-db:
    image: 'postgres:15.5'
    env_file: .env.tests
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  test-django:
    build: .
    command: sh -c "
      python3 manage.py migrate
      && python3 manage.py loaddata -i ./fixture.json
      && python3 manage.py test tests"
    env_file: ./tgbot/.env
    ports:
      - "8000:8000"
    stop_signal: SIGINT
    depends_on:
      test-db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app

