name: Django Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin

    - name: Run Django tests
      run: docker compose -f docker-compose.tests.yml up

    - name: Stop and remove containers
      run: docker compose down
