name: Django Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        legacy: false    # will also install in PATH as `docker-compose`
    - run: docker compose -f docker-compose.tests.yml up
